[build-system]
requires = [
    "setuptools>=58.0.0",
    "setuptools_scm[toml]>=3.4.3",
    "wheel>=0.37.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "dread_editor/version.py"
